### PR TITLE
Automatically create (and embed) ro-crates on changes to notebooks.

### PR DESCRIPTION
**Pull request by harrykeightley**
This PR includes a github action which detects if any notebooks change during pushes to master. If changes exists, it:
1. Creates an individual ro-crate per jupyter notebook and embeds them within the metadata of each notebook (using the "ro-crate" key).
2. Creates a root ro-crate for all the notebooks in the directory.

Notes:
- When pulling data about authorship of individual notebooks, the script will first attempt to look within the metadata of that notebook for a key called `creators`. The value of this should be a list of JSON objects, of the form: 
```[{orcid: 'someOrcid', name: 'someName'}, ...]```. If this key isn't found, the author list will default to the authors described in the `metadata.json` file that's generated during the creation of the repo.
- I would have used the js library for ro-crates, but everything else in this directory is python so it made more sense to do it this way.

### CODE REVIEW

**Comment by wragge** [comment]
Apologies for taking so long to get to this. It's been a hectic few weeks, capped off by a couple of COVID cases in the family.

Could you walk me through the thinking here a bit, as it's not exactly what I was expecting based on our last meeting? My understanding was that an ro-crate would be created by extracting/combining data from the `metadata.json` file, and from metadata embedded within notebooks. I'm not clear on the value of embedding an ro-crate in every notebook, and I'm not sure I'd want to be modifying notebooks on push in this way.

The sort of workflow I was expecting is:

- repository is created with `metadata.json` file
- users make notebooks, and can embed some useful metadata eg: creators, title, description (based on ro-crate/schema.org and with some sort of namespacing?) using the Jupyter interface
- when notebooks are pushed to the repository, the ro-crate is created/updated by combining `metadata.json` with the embedded notebook metadata.
- (additionally I'm hoping I might be able to use the embedded notebook metadata to automatically update the list of notebooks in the README.)

**Comment by harrykeightley** [comment]
No worries,

As far as I can see, the process you've outlined is exactly what happens:
- The repo does get created with a `metadata.json` file, sourced from the original cookiecutter.json file.
- Users can embed ro-crate information in their notebooks using the jupyter interface, with some sensible defaults if they don't add any information. For the author list this means that it is taken from the `metadata.json` file by default.
- When changes to the notebooks in the repo occur, an outer ro-crate file is created which automatically combines the embedded data from each notebook.
- You could very easily autopopulate the README after this last step with a list of the notebooks in the 'outer' ro-crate.

**Comment by benfoley** [comment]
Aha, we noticed that "creators" metadata added to the notebooks top-level metadata object was written to the ro-crate, but other metadata wasn't. It seems that there isn't a particularly well-defined (or tightly-defined) schema for the metadata keys that can be added to a notebook, so rather than trying to parse all possible key:values, let's parse the notebook metadata for a limited bunch of things. 

```
"creators": [{"orcid": "232", "name": "ben"}],
"title": "my notebook",
"description": "this notebook is great",
```

And I suppose it's also worth parsing "authors" as a synonym for creators.

Therefore, changing these values in a notebook's metadata will update the `ro-crate-metadata.json` file, as well as update the `ro-crate` metadata item in the notebook itself. It would be best to recommend that people don't manually change the `ro-crate` metadata item in the notebook, as it gets written by the commit action.

**Comment by harrykeightley** [comment]
I've just updated the scripts to look for "title" and "description" as well as the preexisting "creators" keys within the notebook metadata. The rocrate will attempt to use these values first if they exist in the notebook.
Otherwise:
- The description will default to an empty string 
- The title will be the name of the notebook file
- The creators list will default to that found in metadata.json

**Comment by benfoley** [comment]
Turns out that we shouldn't be embedding rocrate in the notebook metadata. I've removed that from the script so that now it creates one `ro-crate-metadata.json` file per repo. I've also added an `input` value which can be used to relate a notebook to the dataset/collection that it works with.

**Comment by wragge** [comment]
Just catching up with this and seeing where we're at now. Glad we're not putting the ro-crate md into notebooks now, I could see myself getting into all sorts of Git problems. I'll just do a bit of testing and get back to you!

**Comment by wragge** [comment]
The action to create the ro-crate runs on the initial cookie-cutter push, which is fine, but I'm wondering whether it now makes the creation of a separate `metadata.json` file redundant? Wouldn't it be better to add the repo name and description directly into the `rocrate-metadata.json` at the root dataset level? I see from the RO-Crate spec that `name` and `description` SHOULD be added at the root level. Is there a reason to have the separate `metadata.json` file now?

**Comment by wragge** [comment]
Answering my own question -- because the `metadata.json` file gets created when the cookie cutter action is run. And the ro-crate action runs when the new repo is pushed from the cookie cutter details, so doesn't have access to the cookie cutter setup info. So maybe we just live with the duplication.

Or should we just create a basic `rocrate-metadata.json` using the cookie cutter action, containing just the root dataset and creator details. Then when the ro-crate action runs it updates the file with the notebook details. Then we'd only have the one metadata file.

In any case, I still think it'd be good to put the repo name and description into the ro-crate. What do you think?

**Comment by wragge** [comment]
I ended up going a slightly different route. Rather than creating a separate metadata file when cookiecutter runs, I'm creating a simple ro-crate file with the values from `cookiecutter.json`. Then instead of creating a new ro-crate file on every push to the repo, I've created a script to update the ro-crate file whenever needed (before pushing the repo). This makes it possible to make manual edits to the crate. It still reads metadata from notebooks, but does a few extra things like adding linked files, creating actions to document notebook runs and metadata changes etc. I think this suits my workflows. Anyway thanks for the help!

**Pull request merged**
